name: blog
encoding: utf-8
markdown: redcarpet
highlighter: pygments
permalink: pretty
exclude: ['CNAME','README.md']
paginate: 6
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
